import {
  Plane,
  Train,
  Bus,
  Car,
  Navigation,
  Building2,
  ShoppingBag,
  Landmark,
  Waves,
  Globe,
  Stethoscope,
  UtensilsCrossed,
  Film,
  MapPin,
  Store,
  Anchor,
  School,
  GraduationCap,
  Dumbbell,
  Trophy,
  Building,
  Hotel,
  Coffee,
  Briefcase,
  Home,
  type LucideIcon,
} from "lucide-react"

export interface TravelTimeIcon {
  value: string
  label: string
  icon: LucideIcon
}

export const TRAVEL_TIME_ICONS: TravelTimeIcon[] = [
  // Transportation
  { value: "airport", label: "Dubai International Airport", icon: Plane },
  { value: "metro", label: "Metro Station", icon: Train },
  { value: "bus", label: "Bus Station", icon: Bus },
  { value: "road", label: "Sheikh Zayed Road", icon: Navigation },
  { value: "taxi", label: "Taxi", icon: Car },
  
  // Areas & Districts
  { value: "downtown", label: "Downtown Dubai", icon: Building2 },
  { value: "marina", label: "Dubai Marina", icon: Anchor },
  { value: "creek", label: "Dubai Creek Harbour", icon: Waves },
  { value: "jbr", label: "JBR - Jumeirah Beach Residence", icon: Anchor },
  { value: "palm", label: "Palm Jumeirah", icon: Building2 },
  { value: "business-bay", label: "Business Bay", icon: Briefcase },
  { value: "jlt", label: "JLT - Jumeirah Lakes Towers", icon: Building2 },
  { value: "dubai-hills", label: "Dubai Hills", icon: Building2 },
  { value: "dubai-land", label: "Dubai Land", icon: Building2 },
  { value: "dubai-south", label: "Dubai South", icon: Plane },
  { value: "dubai-sports-city", label: "Dubai Sports City", icon: Trophy },
  { value: "dubai-production-city", label: "Dubai Production City", icon: Building },
  { value: "dubai-international-city", label: "Dubai International City", icon: Globe },
  { value: "dubai-media-city", label: "Dubai Media City", icon: Film },
  { value: "dubai-internet-city", label: "Dubai Internet City", icon: Globe },
  { value: "dubai-knowledge-park", label: "Dubai Knowledge Park", icon: GraduationCap },
  { value: "dubai-healthcare-city", label: "Dubai Healthcare City", icon: Stethoscope },
  { value: "dubai-design-district", label: "Dubai Design District", icon: Building },
  { value: "dubai-silicon-oasis", label: "Dubai Silicon Oasis", icon: Building },
  { value: "dubai-waterfront", label: "Dubai Waterfront", icon: Waves },
  { value: "dubai-creek", label: "Dubai Creek", icon: Waves },
  { value: "jumeirah", label: "Jumeirah", icon: Building2 },
  { value: "deira", label: "Deira", icon: Building2 },
  { value: "bur-dubai", label: "Bur Dubai", icon: Building2 },
  { value: "al-barsha", label: "Al Barsha", icon: Building2 },
  { value: "al-quoz", label: "Al Quoz", icon: Building2 },
  { value: "al-wasl", label: "Al Wasl", icon: Building2 },
  
  // Malls & Shopping
  { value: "dubai-mall", label: "Dubai Mall", icon: ShoppingBag },
  { value: "mall-emirates", label: "Mall of the Emirates", icon: Store },
  { value: "mall-arabia", label: "Mall of Arabia", icon: ShoppingBag },
  { value: "city-centre", label: "City Centre Deira", icon: ShoppingBag },
  { value: "city-centre-mirdif", label: "City Centre Mirdif", icon: ShoppingBag },
  { value: "dubai-festival-city", label: "Dubai Festival City", icon: ShoppingBag },
  { value: "dubai-outlet-mall", label: "Dubai Outlet Mall", icon: Store },
  { value: "burjuman", label: "BurJuman", icon: ShoppingBag },
  { value: "wafi-mall", label: "Wafi Mall", icon: Store },
  { value: "gold-souq", label: "Gold Souk", icon: Store },
  { value: "spice-souq", label: "Spice Souk", icon: Store },
  { value: "textile-souq", label: "Textile Souk", icon: Store },
  { value: "dubai-marina-mall", label: "Dubai Marina Mall", icon: ShoppingBag },
  { value: "ibn-battuta-mall", label: "Ibn Battuta Mall", icon: ShoppingBag },
  { value: "dubai-hills-mall", label: "Dubai Hills Mall", icon: ShoppingBag },
  { value: "city-walk", label: "City Walk", icon: ShoppingBag },
  { value: "the-beach", label: "The Beach", icon: ShoppingBag },
  { value: "bluewaters", label: "Bluewaters", icon: ShoppingBag },
  
  // Landmarks & Attractions
  { value: "burj-khalifa", label: "Burj Khalifa", icon: Landmark },
  { value: "global-village", label: "Global Village", icon: Globe },
  { value: "burj-al-arab", label: "Burj Al Arab", icon: Building },
  { value: "palm-fountain", label: "The Palm Fountain", icon: Waves },
  { value: "dubai-fountain", label: "Dubai Fountain", icon: Waves },
  { value: "atlantis", label: "Atlantis The Palm", icon: Building },
  { value: "dubai-aquarium", label: "Dubai Aquarium", icon: Waves },
  { value: "dubai-frame", label: "Dubai Frame", icon: Building },
  { value: "museum-future", label: "Museum of the Future", icon: Building },
  { value: "dubai-opera", label: "Dubai Opera", icon: Building },
  { value: "miracle-garden", label: "Dubai Miracle Garden", icon: Building },
  { value: "butterfly-garden", label: "Dubai Butterfly Garden", icon: Building },
  { value: "aquaventure", label: "Aquaventure Waterpark", icon: Waves },
  { value: "wild-wadi", label: "Wild Wadi Waterpark", icon: Waves },
  { value: "motiongate", label: "Motiongate Dubai", icon: Film },
  { value: "legoland", label: "Legoland Dubai", icon: Building },
  { value: "bollywood-parks", label: "Bollywood Parks", icon: Film },
  { value: "img-worlds", label: "IMG Worlds of Adventure", icon: Film },
  { value: "dubai-parks", label: "Dubai Parks and Resorts", icon: Building },
  { value: "ski-dubai", label: "Ski Dubai", icon: Building },
  { value: "green-planet", label: "The Green Planet", icon: Building },
  { value: "dubai-autodrome", label: "Dubai Autodrome", icon: Car },
  
  // Services & Entertainment
  { value: "hospital", label: "Hospital", icon: Stethoscope },
  { value: "restaurant", label: "Restaurant", icon: UtensilsCrossed },
  { value: "cinema", label: "Cinema", icon: Film },
  { value: "cafe", label: "Cafe", icon: Coffee },
  { value: "hotel", label: "Hotel", icon: Hotel },
  { value: "gym", label: "Gym / Fitness Center", icon: Dumbbell },
  { value: "school", label: "School", icon: School },
  { value: "university", label: "University", icon: GraduationCap },
  { value: "bank", label: "Bank", icon: Building },
  { value: "pharmacy", label: "Pharmacy", icon: Stethoscope },
  { value: "supermarket", label: "Supermarket", icon: ShoppingBag },
  { value: "park", label: "Park", icon: Building2 },
  { value: "beach", label: "Beach", icon: Waves },
  { value: "stadium", label: "Stadium", icon: Trophy },
  { value: "spa", label: "Spa", icon: Waves },
  { value: "salon", label: "Salon", icon: Store },
  { value: "car-wash", label: "Car Wash", icon: Car },
  { value: "gas-station", label: "Gas Station", icon: Car },
  { value: "post-office", label: "Post Office", icon: Building },
  { value: "police-station", label: "Police Station", icon: Building },
  { value: "fire-station", label: "Fire Station", icon: Building },
  { value: "mosque", label: "Mosque", icon: Building },
  { value: "church", label: "Church", icon: Building },
  { value: "library", label: "Library", icon: Building },
  { value: "museum", label: "Museum", icon: Building },
  { value: "theater", label: "Theater", icon: Film },
  { value: "bowling", label: "Bowling Alley", icon: Trophy },
  { value: "golf", label: "Golf Course", icon: Trophy },
  { value: "tennis", label: "Tennis Court", icon: Trophy },
  { value: "swimming", label: "Swimming Pool", icon: Waves },
  { value: "clinic", label: "Clinic", icon: Stethoscope },
  { value: "dentist", label: "Dentist", icon: Stethoscope },
  { value: "vet", label: "Veterinary", icon: Stethoscope },
  { value: "barbershop", label: "Barbershop", icon: Store },
  { value: "laundry", label: "Laundry", icon: Store },
  { value: "dry-cleaner", label: "Dry Cleaner", icon: Store },
  { value: "atm", label: "ATM", icon: Building },
  { value: "parking", label: "Parking", icon: Car },
  { value: "nursery", label: "Nursery / Kindergarten", icon: School },
  { value: "playground", label: "Playground", icon: Building2 },
  { value: "gaming-zone", label: "Gaming Zone", icon: Film },
  { value: "paintball", label: "Paintball", icon: Trophy },
  { value: "karting", label: "Karting", icon: Car },
  
  // Business & Offices
  { value: "office", label: "Office Building", icon: Building },
  { value: "business-center", label: "Business Center", icon: Briefcase },
  { value: "coworking", label: "Coworking Space", icon: Briefcase },
  { value: "government-office", label: "Government Office", icon: Building },
  { value: "embassy", label: "Embassy", icon: Building },
  { value: "court", label: "Court", icon: Building },
  
  // Residential
  { value: "residential", label: "Residential Area", icon: Home },
  { value: "villa", label: "Villa Community", icon: Home },
  { value: "apartment", label: "Apartment Building", icon: Building },
  { value: "compound", label: "Compound", icon: Home },
  
  // Generic
  { value: "location", label: "Location", icon: MapPin },
  { value: "custom", label: "Custom Location", icon: MapPin },
]

export const getTravelTimeIcon = (iconValue: string): TravelTimeIcon | undefined => {
  return TRAVEL_TIME_ICONS.find(icon => icon.value === iconValue)
}
